Resources:
  asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-east-1a
        - us-east-1c
      LaunchConfigurationName: !Ref lc
      MaxSize: 1
      MinSize: 1

  lc:
    Type: AWS::AutoScaling::LaunchConfiguration 
    Properties:
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType: t2.micro